<?php

/**
 * @file
 * Contains my_module.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_preprocess_html().
 */

function my_module_preprocess_html(array &$page) {
  $page['#attached']['library'][] = 'my_module/my_module';
}

/**
 * Implements hook_preprocess_page().
 */
function my_module_preprocess_page(array &$variables) {
  $valuer = \Drupal::config('my_module.settings')->get('example_setting');
  $variables['#attached']['drupalSettings']['my_module'] = $valuer;
}